#!/bin/sh

case "$1" in
purge)
	if [ -L /etc/network/run ] ; then
		rm -f /etc/network/run
	elif [ -d /etc/network/run ] ; then
		rm -f /etc/network/run/ifstate
		rmdir --ignore-fail-on-non-empty /etc/network/run
	fi
	rm -f /etc/network/ifstate
	# Note: We don't remove /etc/network/interfaces
	;;
esac

#DEBHELPER#

